CREATE TABLE SPECIES (
	ID INT(5) NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL
);

CREATE TABLE GENRE (
	ID INT(5) NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL
);

CREATE TABLE AUTHOR (
	ID INT(5) NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	BIOGRAPHY VARCHAR(500) NOT NULL
);

CREATE TABLE CITY (
	ID INT(5) NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	REGION VARCHAR(100) NOT NULL,
	COUNTRY VARCHAR(100) NOT NULL
);

CREATE TABLE PUB_HOUSE (
	ID INT(5) NOT NULL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	CITY_ID INT(5) NOT NULL,
	FOREIGN KEY (CITY_ID) REFERENCES CITY(ID) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE BOOK (
	ID INT(5) NOT NULL PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	PUB_HOUSE_ID INT(5),
	PUB_YEAR INT(4),
	EDITION VARCHAR(10),
	SPECIES_ID INT (5),
	GENRE_ID INT(5),
	DESCRIPTION VARCHAR(300),
	STOCKPILE INT (10),
	PRICE FLOAT (5, 2),
	FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID),
	FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES(ID),
	FOREIGN KEY (PUB_HOUSE_ID) REFERENCES PUB_HOUSE(ID)
);

CREATE TABLE BOOK_AUTHOR (
	ID INT(5) NOT NULL PRIMARY KEY,
	BOOK_ID INT(5),
	AUTHOR_ID INT(5),
	FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID) ON UPDATE CASCADE ON DELETE SET NULL
)